services:
  plugins_kanban:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - ruki_plugins
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  ruki_plugins:
    name: ruki_plugins
  ruki_cloudflared:
    name: ruki_cloudflared
    external: true